# Generated by Django 3.1.2 on 2020-12-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0002_auto_20201202_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Like New', 'Like New'), ('Used', 'Used')], default='Used', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_type',
            field=models.CharField(choices=[('Paperback', 'Paperback'), ('Hardcover Case Wrap', 'Hardcover Case Wrap'), ('Hardcover Dust Jacket', 'Hardcover Dust Jacket')], default='Paperback', max_length=21),
        ),
    ]
